make the default-time-filter enable
apache/kylin pull request #1219
Opened 2020-05-20 09:34 UTC by fengpod

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [ ] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I will prepare another pr against the `document` branch
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-05-20 09:40 UTC, fengpod commented
hi，
When enter or refresh the monitor page，the time-filter be set to LAST ONE WEEK，not the default value in the properties。This pr make the setting effective。

2020-05-22 14:48 UTC, shaofengshi requested changes
Hello, thanks for the PR! Could you please open a JIRA with a description, and then use the JIRA ID in the PR commit message? You can refer to other PRs. Thanks!

2020-05-27 09:03 UTC, shaofengshi commented
merged by manual; Next time please raise to "mater" branch. Thanks for contributing to kylin!

2020-05-27 09:03 UTC, closed without merging

2020-06-11 11:05 UTC, zhangayqian commented
### Check list
- [ ] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [ ] new feature
    - [x] enhancement
- [x] Step 2. Test cases are designed and documented (30 minutes EST).
- [x] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [x] Step 4. Verify and make sure test cases passed.
- [x] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [ ] Step 6. Do more check in user perspective (20 minutes EST)
    - [ ] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [ ] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [x] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

2020-06-11 11:10 UTC, zhangayqian commented
## Test Case
- Set `kylin.web.default-time-filter=1` in kylin/properties
- bin/kylin.sh restart
## Expected result
- Default timefilter is LAST ONE DAY
## Verify test case
![image](https://user-images.githubusercontent.com/31064237/84378692-2993d180-ac17-11ea-9bc2-9087fa32c01d.png)